PORT: 3004
DATABASE: ENC:v1:0mI6F8IXHnwk61gg4jyRMg==::9eb09ba82e6e4a9b4d65b11e88c16e83
HOST: dbportafolio.mysql.database.azure.com
USER: ENC:v1:jjLcKpHr5CBb1EXX7iCtcg==::8e09f9b9978374a660a357c2156aa482
PASSWORD: ENC:v1:TbesNmRBEMhjBC7ZZ441+Q==::26fab0d55b78b4c81d089ac0ad2c0467
ENCRYPTION_KEY: ENC:v1:phkDW/jpNAO90uREyyCha7wmMZ7Rt2xtV5TVxj3PX5E=::13824bed911172b6bda2a94f1c013a14
APP_CLIENTID: ENC:v1:xExAMRENCZ6apbJF26H3bpEhKQujzoWJ7DB9gXMffv8L8Z+Mm3e4le9ztyzwTbf6::3df0f106b412c0f50485a10ff9857f5d
TENANTID: ENC:v1:7fuTnn7dvCROcGwGn7CoAbJP6YpyvtKvzgHelwG4ajv+ruG1sExLTqz/1heweqZR::a8584e1525237e01e98f1ec4033a650d
SECRETVALUE: ENC:v1:kwokwfXJPuMb27pmyqu6m/uot4dXpmDnUekvvF6rIG3kNlk8KPgecomIfP+XBxrb::b5ef8e2ec1112992bb86f1ce39108ff5
LISTID: ENC:v1:D3rR5Tax6IOeOH8Tw1Ct2YVUb1lCzOibYgyDzVpz8mbP/8Hu5tfyU6iNY0/Ex2HN::710564adcdb591676e5adb6ea32e7d8a
DAYS_TIME: 7
AIRTABLE_ACCESSTOKEN: ENC:v1:nn7hmrAqNqhde6qKd+CCw4D/FM1MkqNSROuoat5N3f747tOavOMG+wL66wGwqfLfuAfYodpSjtT6D7gTa8IIS2V7O1L79SdXWxO3uiDe3ipX40/hwq2cbj0fHrSvS0fV::708eb690f6026166bfaca9500c8f3c08
TABLE_ID: ENC:v1:mGPTHBA+Jw9lYBHSXXlsEA84R2TpyCWS0eD03gchaf0=::b335ce213823ff94c52ce15c247a4679
ENV: development
SECRETMAILVALUE: ENC:v1:2vFejfMAIBpipAxfLSpZbxJg9RnAI3r6MmEI3NJ9iYrULxxjIU10uM5b1RIyNyse::02a32f06e4240a9fe5823cf145ba41e5
CLIENTMAILID: ENC:v1:EWqw+RAiuF3yoqFYlaP9R24FmuOq0Tg1rXVyoi7ll3lZDCuHKQ4U2kamfdPFSBJJ::f42f683ee178c2b7206adc40d8ae58ef
SECRETIDMAIL: ENC:v1:bvqWFo6jqzSMhAYq2hCVdqd37F+oGWfnFaqPgnoKLqBAUTmYLBfqR8HOTAyyxtHY::bdd227b09619f2311d084c7e54113a24
SEND_NOTIFICATIONS: ENC:v1:sWGE73+JVern4M05T440Ow==::e690af5950c97f230da24980198f203c
PORTFOLIO_EMAIL: ENC:v1:N4yICWSb99vVm25Yhwi6A5GCdAP0x28XTNNpMAyni3cNOO5i5VD+4JxEtcP8iqBQ::efff614cce7339d74ee50979bffd9bdd
ADMIN_NOTIFICATION_EMAIL: ENC:v1:2gUgAGvzYsckAOyD/myrbWwVbjhAvwTSa8+k0lsqVxFvlejY2DpnQQ7VLsbH96S2::870f1bb87d7dc4a58d4ab2b97abe74d2
ACCOUNT_NAME: ENC:v1:JfGjEVyh4Y0rc//bHQdYD/wVf1REXGEz8bnfZQXNDhY=::8ad69351b9528b26af0ad4976a5db7aa
SAS_TOKEN: ENC:v1:IF8Xw7JAk8M5wk1N2mzRbJ1idudEjOQkmWOm9ByQk1+9VspQYeFB0b+kvZmI1Typwtby6HdoEHYYVgOe4eda/HiWwI1EUL5CKaWhHcPFeomr5+81hj3bfn893ybRXCxEF3HDQK6N5hM7pernfetDxazUB170BeFG8ypx3h4wQwizSTK3vTwTJ0qt4KOLNejchtIjLfm1CY40zE6wsPytSA==::1d7b9d353c6c6e0c513e7d6be9030558
CONTAINER_NAME: ENC:v1:l5Yctue6dDkcDbFNS2ahdQ==::5de4051153b23ea7c075c085689fd111
STORAGE_KEY: ENC:v1:8nIqDJ+nL0YwYmoIbfvVKPCFer7hZeF0tAyTiO8la0tAIL7mOKMt2Ruw4D33raR27iNCK0JbrzHKwr2ywRi+r8T9kzcG+H9Fh8p8PpnfZP52NBfwXsxtOzGNa4UYqCI/::6b3c2fff3f82d4ae8dfea9910fa271e9
AZURE_STORAGE_CONNECTION_STRING: ENC:v1:s4bp/F6S0ZT9MURySbfEVz3nSELeXvERbW48KmGnJtgLC/k5VbL7kQ0ydZwnHTzUkek67qQ4uP39mNuw7Ai1Fwj3M1eo358A9E2Z6SCsKRRmO/F24Vtc+2cjl6hEUNpvzJ+Zo9uNGaoWafZ9YxVLaAsjIL77D0kLhIrwrVNH5jMzhU+vLXTZu8+FNiJ2TRRiNtJeL2CFFGpyOh7GiaoANqwXt9bcppuaEfvb3fw5F7PMPIOItE7lHRYLC//UIDv3oI7ANf+J1yn3hFnObq6TmA==::fb419bc34227ad872d152edba2aad8cd